name: Androidlab
description: UdeA Proyecto MisionTic2022

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/machupicchu.png
    - assets/images/coliseo-de-roma.jpg
    - assets/images/taj-mahal.jpg
    - assets/images/piramegipto.jpg

  uses-material-design: true
